---
name: "Feature request"
description: "Suggest a new feature for the integration"
body:
  - type: markdown
    attributes:
      value: |
        Before you open a new feature request, search through the existing issues to see if someone else has already requested it.
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues and this feature has not been requested before.
          required: true
        - label: This request only contains 1 feature (if you have multiple features, open one request for each).
          required: true
  - type: textarea
    attributes:
      label: "Describe the feature"
      description: "A clear and concise description of the feature you'd like."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Use case"
      description: "Describe the use case for this feature. Why would it be useful?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Proposed solution"
      description: "If you have a specific solution in mind, describe it here."
  - type: textarea
    attributes:
      label: "Alternatives considered"
      description: "Describe any alternative solutions or features you've considered."
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
